import Header from '@/components/header';
import '../styles/globals.css';
import { Inter } from 'next/font/google'


export const metadata = {
  title: 'MERN STACK APP',
  description: 'Generated by Amir Ali Azimloo',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      <Header />
      <div className=" container mx-auto " >
      {children}
      </div>
      </body>
    </html>
  )
}
