import "../styles/globals.css";
import Header from "@/components/header";

export const metadata = {
  title: "MERN STACK APP",
  description: "Generated by Amir Ali Azimloo",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className=" flex flex-col gap-12">
          <Header />
          <div className=" container mx-auto flex flex-col gap-12">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
